//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bll
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.RESERVE_DB = new HashSet<RESERVE_DB>();
        }
    
        public int TIC_CAT_ID { get; set; }
        public int EVENT_ID { get; set; }
        public string CAT_NAME { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string NUM_OF_TICKET { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVE_DB> RESERVE_DB { get; set; }
        public virtual EVENTS EVENTS { get; set; }
    }
}
